== GitHub integration plugin

=== Pull Requests Trigger
==== Triggering
- Configure https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin[github-plugin] according to it's documentation.
- Set `GitHub project property` with link to your GitHub repository in Job settings.
- Configure https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin[git-plugin]: add any repo name i.e. 'origin-pull' and set refspec to
`+refs/pull/${GITHUB_PR_NUMBER}/merge:refs/remotes/origin-pull/pull/${GITHUB_PR_NUMBER}/merge` if you want run
build for merged state or '/head' for building exact PR commits, or `$GITHUB_PR_COND_REF` if you want 'head' state
when PR is not mergeable (according to GH state). Set branch specifier to `origin-pull/pull/${GITHUB_PR_NUMBER}/merge`.
This exact link allows to speedup fetch sources.
- Enable "Build GitHub Pull Requests" trigger and configure it.
- If you want do gatekeepering, then add second repository with i.e. origin.
Add `Merge` extension in from Git SCM and configure post build action for push action.

==== Commit/PR statuses
- If you want to set commit status right before job was put to Jenkins queue, enable `Set status before build` checkbox
in trigger configuration (it will have no links because there is no real builds in jenkins, only queue item
that is not a build)
- In `Build` section `Add Build step` called `GitHub PR: set pull request status to "pending"` and enter some message
like `Build #${BUILD_NUMBER} started`
- In `Post-build Actions` add `GitHub PR: set PR status` and configure message to `Build #${BUILD_NUMBER} ended`

=== Branch Trigger
- Configure https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin[github-plugin] according to it's documentation.
- Set `GitHub project property` with link to your GH repository in Job settings.
- Configure Git